export const projects = [
  {
    title: "Musée Maritime",
    images: ["./public/_museem.webp", "./public/_mm2.webp"],
    year: 2025,
    href: "./sample-project",
    tags: ["COMMUNICATION", "CAMPAIGN", "AD"],
  },
  {
    title: "Moonrush",
    images: ["./public/_moonrush.webp", "./public/_mr2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["DESIGN", "BRANDING"],
  },
  {
    title: "Suapse",
    images: ["./public/_suapse.webp", "./public/_suapse2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["DIGITAL", "INTERACTIVE"],
  },
  {
    title: "TMG",
    images: ["./public/_tmg.webp", "./public/_tmg2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["ART", "PHOTOGRAPHY"],
  },
  {
    title: "Fête de la musique",
    images: ["./public/_fmusique.webp", "./public/_fdlm2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["MOTION", "VIDEO"],
  },
  {
    title: "Basique",
    images: ["./public/_basique.webp", "./public/_basique2.webp"],
    year: 2022,
    href: "./sample-project",
    tags: ["ANIMATION", "3D"],
  },
  {
    title: "Chatelaillon",
    images: ["./public/_chatel.webp", "./public/_chatel2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["CAMPAIGN", "PRINT"],
  },
  {
    title: "Book Tons",
    images: ["./public/_bookt2.webp", "./public/_bookt2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["WEB", "UX/UI"],
  },
  {
    title: "Marché Créatif",
    images: ["./public/_marche.webp", "./public/_marche2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["BRANDING", "IDENTITY"],
  },
  {
    title: "Spontex",
    images: ["./public/_spontex.webp", "./public/_spontex2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["DIGITAL", "AD"],
  },
  {
    title: "Francofolies",
    images: ["./public/_franco.webp"],
    year: 2022,
    href: "./sample-project",
    tags: ["PHOTOGRAPHY", "EDITORIAL"],
  },
  {
    title: "Pixii Festival",
    images: ["./public/_pixii.webp", "./public/_pixii2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["FASHION", "CAMPAIGN"],
  },
  {
    title: "Lyon Biennale",
    images: ["./public/_lyonbien.webp", "./public/_lyonb2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["DESIGN", "PRODUCT"],
  },
  {
    title: "Neonflow",
    images: ["./public/_neonflow.webp", "./public/_neonflow2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["MOTION", "BRANDING"],
  },
  {
    title: "Wilee",
    images: ["./public/_wilee.webp", "./public/_wilee2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["ART", "INSTALLATION"],
  },
  {
    title: "Synthèse",
    images: ["./public/_synthese.webp", "./public/_synt2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["INTERACTIVE", "DIGITAL"],
  },
  {
    title: "Serre Rochelaise",
    images: ["./public/_bota.webp", "./public/_bota2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["ANIMATION", "CAMPAIGN"],
  },
  {
    title: "Rouge aux lèvres",
    images: ["./public/_beaujolais.webp", "./public/_beaujolais2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["VIDEO", "DOCUMENTARY"],
  },
  {
    title: "City guide",
    images: ["./public/_maplr.webp", "./public/_maplr2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["BRANDING", "CAMPAIGN"],
  },
  {
    title: "Almanak",
    images: ["./public/_almanak.webp", "./public/_almanak2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["PHOTOGRAPHY", "TRAVEL"],
  },
  {
    title: "Ideocentre",
    images: ["./public/_ideo.webp", "./public/_ideo2.webp"],
    year: 2022,
    href: "./sample-project",
    tags: ["3D", "DESIGN"],
  },
  {
    title: "Ricoré",
    images: ["./public/_rico.webp", "./public/_rico2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["WEB", "INTERACTIVE"],
  },
  {
    title: "Graphika",
    images: ["./public/_graphika.webp", "./public/_graphika2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["MOTION", "AD"],
  },
  {
    title: "Redbull campaign",
    images: ["./public/_red.webp", "./public/_red2.webp"],
    year: 2022,
    href: "./sample-project",
    tags: ["DESIGN", "TECH"],
  },
  {
    title: "Archipel",
    images: ["./public/_archipel.webp", "./public/_archipel2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["CAMPAIGN", "FASHION"],
  },
  {
    title: "Théâtre de Belleville",
    images: ["./public/_bellev.webp", "./public/_belleville.webp"],
    year: 2024,
    href: "https://portfolio-elytra.webflow.io/theatre-belleville",
    tags: ["CAMPAIGN", "FASHION"],
  },
  {
    title: "Fête de la Saint-Jean",
    images: ["./public/_saintjean.webp", "./public/_saintj2.webp"],
    year: 2024,
    href: "https://portfolio-elytra.webflow.io/",
    tags: ["CAMPAIGN", "FASHION"],
  },  
  {
    title: "Tryyland",
    images: ["./public/_tryyland.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["CAMPAIGN", "FASHION"],
  },
  {
    title: "Michel Crépeau",
    images: ["./public/_mediatheque.webp", "./public/_mc2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["CAMPAIGN", "FASHION"],
  },
  {
    title: "Atelier Écriture",
    images: ["./public/_ecriture.webp", "./public/_ecriture2.webp"],
    year: 2024,
    href: "https://portfolio-elytra.webflow.io/atelier-ecriture",
    tags: ["CAMPAIGN", "FASHION"],
  },
];