export const projects = [
  {
    title: "Musée Maritime",
    images: ["./public/museem.webp", "./public/mm2.webp"],
    year: 2025,
    href: "./sample-project",
    tags: ["COMMUNICATION", "CAMPAIGN", "AD"],
  },
  {
    title: "Moonrush",
    images: ["./public/moonrush.webp", "./public/mr2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["DESIGN", "BRANDING"],
  },
  {
    title: "Suapse",
    images: ["./public/suapse.webp", "./public/suapse2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["DIGITAL", "INTERACTIVE"],
  },
  {
    title: "TMG",
    images: ["./public/tmg.webp", "./public/tmg2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["ART", "PHOTOGRAPHY"],
  },
  {
    title: "Fête de la musique",
    images: ["./public/fmusique.webp", "./public/fdlm2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["MOTION", "VIDEO"],
  },
  {
    title: "Basique",
    images: ["./public/basique.webp", "./public/basique2.webp",],
    year: 2022,
    href: "./sample-project",
    tags: ["ANIMATION", "3D"],
  },
  {
    title: "Chatelaillon",
    images: ["./public/chatel.webp", "./public/chatel2.webp",],
    year: 2024,
    href: "./sample-project",
    tags: ["CAMPAIGN", "PRINT"],
  },
  {
    title: "Book Tons",
    images: ["./public/tonbook.webp", "./public/bookt2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["WEB", "UX/UI"],
  },
  {
    title: "Marché Créatif",
    images: ["./public/marche.webp", "./public/marche2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["BRANDING", "IDENTITY"],
  },
  {
    title: "Spontex",
    images: ["./public/spontex.webp", "./public/spontex2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["DIGITAL", "AD"],
  },
  {
    title: "Francofolies",
    images: ["./public/franco.webp"],
    year: 2022,
    href: "./sample-project",
    tags: ["PHOTOGRAPHY", "EDITORIAL"],
  },
  {
    title: "Pixii Festival",
    images: ["./public/pixii.webp", "./public/pixii2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["FASHION", "CAMPAIGN"],
  },
  {
    title: "Lyon Biennale",
    images: ["./public/lyonbien.webp", "./public/lyonb2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["DESIGN", "PRODUCT"],
  },
  {
    title: "Neonflow",
    images: ["./public/neonflow.webp", "./public/neonflow2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["MOTION", "BRANDING"],
  },
  {
    title: "Wilee",
    images: ["./public/wilee.webp", "./public/wilee2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["ART", "INSTALLATION"],
  },
  {
    title: "Synthèse",
    images: ["./public/synthese.webp", "./public/synt2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["INTERACTIVE", "DIGITAL"],
  },
  {
    title: "Serre Rochelaise",
    images: ["./public/bota.webp", "./public/bota2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["ANIMATION", "CAMPAIGN"],
  },
  {
    title: "Rouge aux lèvres",
    images: ["./public/beaujolais.webp", "./public/beaujolais2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["VIDEO", "DOCUMENTARY"],
  },
  {
    title: "City guide",
    images: ["./public/maplr.webp", "./public/maplr2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["BRANDING", "CAMPAIGN"],
  },
  {
    title: "Almanak",
    images: ["./public/almanak.webp", "./public/almanak2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["PHOTOGRAPHY", "TRAVEL"],
  },
  {
    title: "Ideocentre",
    images: ["./public/ideo.webp", "./public/ideo2.webp"],
    year: 2022,
    href: "./sample-project",
    tags: ["3D", "DESIGN"],
  },
  {
    title: "Ricoré",
    images: ["./public/rico.webp", "./public/rico2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["WEB", "INTERACTIVE"],
  },
  {
    title: "Graphika",
    images: ["./public/graphika.webp", "./public/graphika2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["MOTION", "AD"],
  },
  {
    title: "Redbull campaign",
    images: ["./public/red.webp", "./public/red2.webp"],
    year: 2022,
    href: "./sample-project",
    tags: ["DESIGN", "TECH"],
  },
  {
    title: "Archipel",
    images: ["./public/archipel.webp", "./public/archipel2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["CAMPAIGN", "FASHION"],
  },
    {
    title: "Théâtre de Belleville",
    images: ["./public/bellev.webp", "./public/belleville.webp"],
    year: 2024,
    href: "https://portfolio-elytra.webflow.io/theatre-belleville",
    tags: ["CAMPAIGN", "FASHION"],
  },
    {
    title: "Fête de la Saint-Jean",
    images: ["./public/saintjean.webp", "./public/saintj2.webp"],
    year: 2024,
    href: "https://portfolio-elytra.webflow.io/",
    tags: ["CAMPAIGN", "FASHION"],
  },  
  {
    title: "Tryyland",
    images: ["./public/tryyland.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["CAMPAIGN", "FASHION"],
  },
    {
    title: "Michel Crépeau",
    images: ["./public/mediatheque.webp", "./public/mc2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["CAMPAIGN", "FASHION"],
  },
    {
    title: "Atelier Écriture",
    images: ["./public/ecriture.webp", "./public/ecriture2.webp"],
    year: 2024,
    href: "https://portfolio-elytra.webflow.io/atelier-ecriture",
    tags: ["CAMPAIGN", "FASHION"],
  },
];